### ISSUE TITLE
Ability to write to the file

### ISSUE THREAD

**Issue by pliablepixels** [rypan/jekyll-db#1]
Hi there, thank you for this excellent template. This is not really an issue, more of a question: I was curious if you found a way to host it on github and yet be able to write to the data file via a form? I'm looking at creating a new page that creates a form driven approach to entering the data and then automatically writing it to the data file instead of having to manually edit it.

**Comment by rypan** [comment]
Hello! :)

I _think_ it's possible. @benbalter created a hosted form that would update a csv: https://github.com/benbalter/github-forms. I bet it could be adapted to create new markdown files that power each row.

**Comment by pliablepixels** [comment]
Very cool - thank you!
